const initialData = {
  siteSettings: [
    { setting_key: 'site_name', setting_value: 'Shree Dipeshwari Engineering', setting_group: 'general' },
    { setting_key: 'tagline', setting_value: 'Complete Polymer Solution', setting_group: 'general' },
    { setting_key: 'hero_eyebrow', setting_value: 'Vadodara, Gujarat · Manufacturer', setting_group: 'hero' },
    { setting_key: 'hero_title', setting_value: 'Precision Industrial Sealing & Engineering Polymer Solutions', setting_group: 'hero' },
    { setting_key: 'hero_lead', setting_value: 'Manufacturer of Rubber Moulded Parts, O-Rings, Oil Seals, PTFE, PU, Nylon & Silicone components — engineered to your drawing, in any shore hardness, for mining, cement, pharma, chemical and heavy engineering industries.', setting_group: 'hero' },
    { setting_key: 'about_eyebrow', setting_value: 'About SDE', setting_group: 'about' },
    { setting_key: 'about_title', setting_value: 'Two decades of polymer engineering, built on custom manufacturing.', setting_group: 'about' },
    { setting_key: 'about_text', setting_value: 'Shree Dipeshwari Engineering manufactures and supplies high-performance polyurethane, rubber, PTFE, nylon and silicone components for industrial applications across India and international markets. From 25A to 95A shore hardness, from vacuum bellows to 1400°C fireproof high-temperature bellows — every part is engineered to your size, shape, colour and specification.', setting_group: 'about' },
    { setting_key: 'company_address', setting_value: 'FF-13, Divine Galaxy, Nr. Lotus Court, Opp. C.M. Patel Farm, Kalali Village Road, Vadodara – 390012, Gujarat, India', setting_group: 'contact' },
    { setting_key: 'primary_phone', setting_value: '+919924314732', setting_group: 'contact' },
    { setting_key: 'primary_phone_display', setting_value: '+91 9924 314732', setting_group: 'contact' },
    { setting_key: 'secondary_phone', setting_value: '+919313860251', setting_group: 'contact' },
    { setting_key: 'secondary_phone_display', setting_value: '+91 93138 60251', setting_group: 'contact' },
    { setting_key: 'contact_email', setting_value: 'shreedipeshwariengg@gmail.com', setting_group: 'contact' },
    { setting_key: 'working_hours', setting_value: 'Mon–Sat, 9:30 AM – 7:00 PM', setting_group: 'contact' },
    { setting_key: 'whatsapp_number', setting_value: '919924314732', setting_group: 'contact' },
    { setting_key: 'map_query', setting_value: 'Kalali Village Road, Vadodara 390012', setting_group: 'contact' }
  ],

  heroStats: [
    { num: '25A–95A', lbl: 'Shore Hardness Range', order_index: 1 },
    { num: '1400°C', lbl: 'High-Temp Bellows Rated', order_index: 2 },
    { num: '10+', lbl: 'Polymer Product Lines', order_index: 3 },
    { num: '2 Decades', lbl: 'Trusted Manufacturing', order_index: 4 }
  ],

  specsTicker: [
    { material: 'NBR · SBR · SILICONE · EPDM', details: 'RUBBER MOULDED COMPONENTS', order_index: 1 },
    { material: 'PTFE', details: 'VIRGIN / GLASS FILLED / CARBON FILLED / BRONZE FILLED / PEEK FILLED', order_index: 2 },
    { material: 'PU', details: '25A TO 95A SHORE HARDNESS HIGH-REBOUND', order_index: 3 },
    { material: 'SEALS', details: 'U-CUP / WIPER / V-PACKING / PISTON / GUIDE RINGS', order_index: 4 },
    { material: 'NYLON', details: 'PP / HDPE / PVC / POM / PE MACHINED COMPONENTS', order_index: 5 },
    { material: 'BELLOWS', details: 'FIREPROOF RATED 1200°C TO 1400°C', order_index: 6 }
  ],

  categories: [
    { code: 'P-01', name: 'O-Rings & Oil Seals', description: 'NBR, SBR, Silicone, EPDM — oil-proof, flame-protected, 99% hardness.', order_index: 1 },
    { code: 'P-02', name: 'Hydraulic & Pneumatic Seals', description: 'U-cup, wiper, V-packing, piston, guide & backup rings.', order_index: 2 },
    { code: 'P-03', name: 'PTFE Products', description: 'Rods, bushes, moulded & skived sheets, pipes, machined gaskets.', order_index: 3 },
    { code: 'P-04', name: 'PU Products', description: 'Blocks, pads, sheets, rods, tubes, rings, sleeves & wheels.', order_index: 4 },
    { code: 'P-05', name: 'Nylon Components', description: 'Nylon, PP, HDPE, PVC, POM rods, sheets, profiles & machine parts.', order_index: 5 },
    { code: 'P-06', name: 'Rubber Sheets & Mats', description: 'Checkered sheets, rib mats, insulated mats, cork sheets.', order_index: 6 },
    { code: 'P-07', name: 'Silicone Products', description: 'Hoses, gaskets, diaphragms, sleeves & vacuum bellows.', order_index: 7 },
    { code: 'P-08', name: 'Bellows', description: 'Rubber, PTFE, silicone & high-temperature expansion bellows.', order_index: 8 },
    { code: 'P-09', name: 'Gaskets', description: 'FFKM, Viton, Silicone, Neoprene, EPDM & PTFE grades.', order_index: 9 },
    { code: 'P-10', name: 'Custom Rubber Moulding', description: 'Diaphragms, bush & stoppers, seals, washers, import substitutes.', order_index: 10 },
    { code: 'P-11', name: 'Service & Assortment Kits', description: 'O-ring service kits, internal & external circlip assortment boxes for maintenance stores.', order_index: 11 }
  ],

  products: [
    {
      category_code: 'P-04',
      name: 'PU Wheels & Re-coating',
      slug: 'pu-wheels-recoating',
      subtitle: 'Long service life polyurethane wheels & refurbishment',
      short_desc: 'Long service life PU wheels for industrial equipment & trolleys. Recoat the metal hub instead of replacing it — avoids retooling cost.',
      full_desc: 'Custom-cast polyurethane wheels engineered for heavy load-bearing trolleys, automated guided vehicles (AGVs), stackers, and material handling systems. Available in custom core hub rebonding and re-coating to drastically reduce maintenance downtime and operational replacement expense.',
      material_grades: 'Cast Polyurethane (TDI/MDI-based), High-Rebound PU',
      shore_hardness: '25A–95A Shore',
      temp_rating: '-30°C to +90°C',
      applications: 'Heavy Material Handling, Forklifts, AGVs, Factory Overhead Cranes, Trolleys',
      features: 'High abrasion resistance, floor non-marking, hub recoating service, custom durometer',
      image_url: '/uploads/products/pu-wheels-assortment.jpg',
      gallery_images: ['/uploads/products/pu-drive-wheels.jpg'],
      is_featured: true,
      order_index: 1
    },
    {
      category_code: 'P-03',
      name: 'PTFE Machined Components',
      slug: 'ptfe-machined-components',
      image_url: '/uploads/products/ptfe-machined-components.jpg',
      subtitle: 'Chemical inert & high heat polymer solutions',
      short_desc: 'Gaskets, valve components & bellows in Virgin, Glass Filled, Carbon Filled, Bronze Filled & PEEK Filled grades.',
      full_desc: 'Precision CNC turned and machined PTFE components designed for ultra-aggressive chemical environments and extreme thermal applications. Available in both 100% virgin polymer or reinforced composites for superior dimensional stability under mechanical load.',
      material_grades: 'Virgin PTFE, 15%/25% Glass Filled, Carbon Filled, Bronze Filled, PEEK Filled',
      shore_hardness: '55D–65D Shore',
      temp_rating: '-200°C to +260°C',
      applications: 'Chemical Reactors, Valve Liners, Rotary Seals, Laboratory Apparatus, Cryogenics',
      features: 'Complete chemical resistance, zero stick-slip friction, FDA compliance, high dielectric strength',
      is_featured: true,
      order_index: 2
    },
    {
      category_code: 'P-02',
      name: 'Industrial Hydraulic & Pneumatic Seal Kits',
      slug: 'seal-kits',
      image_url: '/uploads/products/hydraulic-seal-kit.jpg',
      gallery_images: ['/uploads/products/hydraulic-cylinder-seal-diagram.jpg'],
      subtitle: 'High pressure dynamic & static sealing assemblies',
      short_desc: 'U-cup, wiper, V-packing, wear rings, piston & guide rings for mining, construction, cement & granite equipment.',
      full_desc: 'Comprehensive sealing solution designed to withstand pressure spikes up to 700 bar. Engineered using hybrid polyurethane, filled PTFE, and fluoroelastomers to ensure zero hydraulic fluid leakage and extended cylinder barrel lifetime.',
      material_grades: 'PU 95A, NBR 70/90, Viton/FKM, Fabric Reinforced NBR, PTFE bronze',
      shore_hardness: '70A–95A Shore / 60D',
      temp_rating: '-40°C to +150°C',
      applications: 'Hydraulic Cylinders, Heavy Earthmoving Excavators, Cement Presses, Injection Moulding',
      features: 'Extrusion resistant, low friction guide rings, high wipe efficiency against dirt/abrasives',
      is_featured: true,
      order_index: 3
    },
    {
      category_code: 'P-07',
      name: 'Pharma & Food Grade Silicone Gaskets',
      slug: 'pharma-silicone-gaskets',
      subtitle: 'Hygienic FDA compliant sanitary seals',
      short_desc: 'Door gaskets, tri-clover gaskets, validation gaskets & NovAseptic diaphragms for critical hygienic applications.',
      full_desc: 'Ultra-clean Platinum-cured and peroxide-cured silicone elastomer seals designed for pharmaceutical bio-reactors, cleanroom autoclaves, and food processing pipelines. Complies with FDA 21 CFR 177.2600 and USP Class VI requirements.',
      material_grades: 'Platinum Cured Silicone, Translucent Food-Grade Silicone, USP Class VI Silicone',
      shore_hardness: '30A–80A Shore',
      temp_rating: '-60°C to +230°C',
      applications: 'Pharma Cleanrooms, Autoclaves, Tri-Clamp Sanitary Unions, Food Dairy Processing, Bio-reactors',
      features: 'Non-toxic, odourless, zero leeching, steam autoclavable, transparent/colored',
      is_featured: true,
      order_index: 4
    },
    {
      category_code: 'P-08',
      name: 'High Temperature Fireproof Bellows',
      slug: 'high-temp-bellows',
      subtitle: 'Extreme thermal furnace & exhaust expansion joints',
      short_desc: 'Fabric & PTFE bellows for furnace-side use — fireproof and rated up to 1400°C.',
      full_desc: 'Multilayer engineered flexible expansion joints and thermal compensation bellows fabricated with ceramic fiber, high-grade fiberglass fabric, PTFE foil barriers, and stainless steel internal wire mesh reinforcements for high velocity hot gas ducted ducts.',
      material_grades: 'Ceramic Fabric, Fiberglass Silicone Coated, PTFE Inversion Layer, SS316 Wire Reinforcement',
      shore_hardness: 'Custom Flexible Multi-Layer',
      temp_rating: 'Up to +1400°C',
      applications: 'Cement Kilns, Thermal Power Plant Flue Gas Ducts, Steel Smelting Furnaces, Turbine Exhaust',
      features: 'Rated 1200°C–1400°C, absorbs multi-axial duct thermal expansion, acid corrosion resistance',
      is_featured: true,
      order_index: 5
    },
    {
      category_code: 'P-01',
      name: 'Custom Rubber Moulded Gaskets & Diaphragms',
      slug: 'rubber-moulded-gaskets-diaphragms',
      image_url: '/uploads/products/custom-moulded-rubber-parts.jpg',
      subtitle: 'Precision moulded elastomeric sealing components',
      short_desc: 'FFKM, Viton, Silicone, Neoprene & EPDM gaskets — high & low temperature resistant, non-contaminating.',
      full_desc: 'Custom tool-moulded rubber parts engineered to custom 2D/3D CAD drawings or physical reverse-engineered samples. In-house rubber compounding ensures exact shore hardness, chemical resistance, and tensile durability for mission-critical industrial duties.',
      material_grades: 'FFKM (Perfluoroelastomer), Viton (FKM), EPDM, Neoprene (CR), Nitrile (NBR), Natural Rubber',
      shore_hardness: '40A–90A Shore',
      temp_rating: '-50°C to +315°C',
      applications: 'Pumps, High Pressure Pipeline Flanges, Chemical Dosing, Fuel Metering Valves, Compressors',
      features: 'Zero leakage guarantee, oil-proof, ozone and UV resistant, exact dimensional accuracy',
      is_featured: true,
      order_index: 6
    },
    {
      category_code: 'P-05',
      name: 'Machined Engineering Nylon & POM Parts',
      slug: 'nylon-pom-components',
      image_url: '/uploads/products/nylon-engineering-plastics.jpg',
      subtitle: 'Self-lubricating thermoplastic engineering bushes & gears',
      short_desc: 'Nylon 6, PA66, POM (Delrin), UHMW-PE & HDPE precision wear strips, gears, and bushes.',
      full_desc: 'High molecular engineering plastic components machined to micron tolerances for conveyor systems, chemical baths, and low-noise mechanical transmissions.',
      material_grades: 'Nylon 6, Cast Nylon (PA6G), POM Delrin, UHMW-PE, HDPE, PEEK',
      shore_hardness: '80D–90D Shore',
      temp_rating: '-40°C to +120°C',
      applications: 'Conveyor Guides, Bottling Plants, Drive Gears, Insulating Washers, Star Wheels',
      features: 'Lightweight, self-lubricating, zero corrosion, high impact resistance',
      is_featured: false,
      order_index: 7
    },
    {
      category_code: 'P-06',
      name: 'Industrial Rubber Sheets & Electrical Insulated Mats',
      slug: 'rubber-sheets-insulated-mats',
      image_url: '/uploads/products/rubber-sheet-rolls.jpg',
      subtitle: 'High voltage electrical switchboard and vibration isolation sheets',
      short_desc: 'IS 15652 / IS 5424 certified electrical insulating mats, neoprene, nitrile and natural rubber rolls.',
      full_desc: 'Heavy-duty industrial rubber floor coverings and sealing sheets suitable for electrical substations, vibration damping, and gasket cutting.',
      material_grades: 'Electrical Grade Elastomer, Neoprene, Nitrile, EPDM, SBR, Cork-Rubber Composite',
      shore_hardness: '55A–75A Shore',
      temp_rating: '-25°C to +100°C',
      applications: 'High-Voltage Switchboards, Substation Flooring, Acoustic & Vibration Isolation, Gasket Sheet Stock',
      features: 'Dielectric strength tested, oil/acid resistant, non-slip textured finish',
      is_featured: false,
      order_index: 8
    },
    {
      category_code: 'P-10',
      name: 'Import Substitute Custom Rubber Moulding',
      slug: 'import-substitute-moulding',
      image_url: '/uploads/products/rubber-moulded-parts-assortment.jpg',
      subtitle: 'Reverse engineering of legacy and overseas polymer components',
      short_desc: 'Fast prototyping and exact dimensional matching for imported machinery spares.',
      full_desc: 'Direct domestic replacement for obsolete or high-cost imported rubber and polyurethane spares. We recreate tool moulds directly from your worn sample part with zero compromise on tensile rating and chemical compatibility.',
      material_grades: 'All Elastomers & Polymers tailored to working medium',
      shore_hardness: '20A to 95A Shore',
      temp_rating: 'Custom engineered',
      applications: 'Imported Extruders, European Machinery, Specialized Hydraulic Pumps, Heavy Presses',
      features: 'Reverse engineering from sample, drastic cost savings, quick lead times',
      is_featured: false,
      order_index: 9
    },
    {
      category_code: 'P-01',
      name: 'Rubber O-Rings',
      slug: 'rubber-o-rings',
      image_url: '/uploads/products/o-rings.jpg',
      subtitle: 'Metric & inch size O-rings in every elastomer grade',
      short_desc: 'NBR, Viton, Silicone & EPDM O-rings in standard metric/AS568 sizes and custom diameters for static and dynamic sealing.',
      full_desc: 'Precision moulded O-rings for hydraulic, pneumatic, vacuum and fluid-handling applications. Supplied in standard metric and AS568 inch sizes or moulded to any custom ID × cross-section, with colour-coded compounds for easy identification of material grade on the shop floor.',
      material_grades: 'NBR (Nitrile), Viton (FKM), Silicone (VMQ), EPDM, Neoprene, HNBR',
      shore_hardness: '50A–90A Shore',
      temp_rating: '-55°C to +230°C (grade dependent)',
      applications: 'Hydraulic Cylinders, Pumps & Valves, Pipe Fittings, Compressors, Pneumatic Tools',
      features: 'Tight dimensional tolerances, colour-coded grades, custom sizes, fuel/oil/steam resistant options',
      is_featured: true,
      order_index: 10
    },
    {
      category_code: 'P-01',
      name: 'Rubber O-Ring Cord',
      slug: 'rubber-o-ring-cord',
      image_url: '/uploads/products/rubber-cord.jpg',
      subtitle: 'Solid round extruded cord for splicing custom O-rings',
      short_desc: 'Solid round NBR, Viton, EPDM & Silicone cord in coils — cut and joint to make large-diameter O-rings and door seals on site.',
      full_desc: 'Extruded solid round rubber cord supplied in continuous coils. Ideal for fabricating oversized O-rings, tank lid seals and groove packing where a moulded ring is impractical. Can be vulcanised or bonded at the joint to form endless rings of any diameter.',
      material_grades: 'NBR, Viton (FKM), EPDM, Silicone, Neoprene',
      shore_hardness: '60A–80A Shore',
      temp_rating: '-40°C to +200°C (grade dependent)',
      applications: 'Large Flange Grooves, Tank & Manhole Covers, Oven Doors, Panel Sealing, Maintenance Stores',
      features: 'Available 2mm–30mm diameter, cut-to-length, vulcanised joints on request',
      is_featured: false,
      order_index: 11
    },
    {
      category_code: 'P-02',
      name: 'PU Hydraulic Seals — U-Cup, Wiper & Guide Band',
      slug: 'pu-hydraulic-seals',
      image_url: '/uploads/products/pu-hydraulic-seals.jpg',
      subtitle: 'Machined polyurethane rod, piston & wiper seals',
      short_desc: 'Polyurethane U-cups, rod wipers, guide/wear bands and O-rings — machined to size for any hydraulic or pneumatic cylinder.',
      full_desc: 'High-performance polyurethane seals CNC-machined from tube stock, so any non-standard size can be supplied without tooling cost. Range includes single and double-lip U-cups, metal-cased and snap-in wipers, fabric/PTFE guide bands and backup rings for complete cylinder resealing.',
      material_grades: 'Hydrolysis-resistant PU 93A–95A, Phenolic Fabric, Bronze-filled PTFE, NBR',
      shore_hardness: '90A–95A Shore',
      temp_rating: '-35°C to +110°C',
      applications: 'Hydraulic Cylinders, Earthmoving Equipment, Presses, Pneumatic Actuators, Injection Moulding Machines',
      features: 'Up to 400 bar, extrusion resistant, excellent wear life, any size without mould cost',
      is_featured: true,
      order_index: 12
    },
    {
      category_code: 'P-03',
      name: 'PTFE Rods, Tubes & Carbon-Filled Bushes',
      slug: 'ptfe-rods-tubes-bushes',
      image_url: '/uploads/products/ptfe-rods-bushes.jpg',
      subtitle: 'Virgin and filled PTFE semi-finished stock & bushes',
      short_desc: 'Virgin PTFE rods, tubes, sheets and carbon/graphite-filled PTFE flanged bushes and thrust washers.',
      full_desc: 'Moulded and extruded PTFE rods, tubes and sheets for in-house machining, plus finished carbon- and graphite-filled PTFE bushes and washers. Filled grades offer higher compressive strength and lower creep for dry-running bearing and sliding applications.',
      material_grades: 'Virgin PTFE, 25% Carbon Filled, Graphite Filled, Glass Filled, Bronze Filled PTFE',
      shore_hardness: '55D–65D Shore',
      temp_rating: '-200°C to +260°C',
      applications: 'Dry-Running Bearings, Valve Seats, Chemical Pumps, Electrical Insulators, Slide Pads',
      features: 'Self-lubricating, chemically inert, low creep filled grades, custom machined sizes',
      is_featured: false,
      order_index: 13
    },
    {
      category_code: 'P-04',
      name: 'PU Rods, Sheets & Tubes',
      slug: 'pu-rods-sheets-tubes',
      image_url: '/uploads/products/pu-rods-sheets-tubes.jpg',
      subtitle: 'Cast polyurethane semi-finished stock in multiple hardnesses',
      short_desc: 'Cast PU rods, hollow tubes, flat sheets and square bars in colour-coded hardness grades for machining wear parts.',
      full_desc: 'Cast polyurethane stock shapes supplied in a wide range of diameters and thicknesses. Colour-coded by shore hardness, they are machined into scraper blades, buffers, rollers, liners and wear strips that outlast rubber and steel in abrasive duty.',
      material_grades: 'Polyester PU, Polyether PU, MDI & TDI based cast PU',
      shore_hardness: '60A–95A Shore',
      temp_rating: '-30°C to +90°C',
      applications: 'Scraper Blades, Chute Liners, Buffers, Rollers, Press Tool Strippers, Wear Strips',
      features: 'Superior abrasion & tear resistance, oil resistant, easy to machine, colour-coded hardness',
      is_featured: false,
      order_index: 14
    },
    {
      category_code: 'P-06',
      name: 'Cork Sheets',
      slug: 'cork-sheets',
      image_url: '/uploads/products/cork-sheets.jpg',
      subtitle: 'Agglomerated cork & cork-rubber gasket sheets',
      short_desc: 'Natural and rubber-bonded cork sheets for gasket cutting, anti-vibration and oil-sealing applications.',
      full_desc: 'Compressible agglomerated cork and cork-rubber composite sheets that conform to uneven flange surfaces. Widely used for transformer, gearbox and engine cover gaskets where oil resistance with low bolt load is required.',
      material_grades: 'Natural Agglomerated Cork, Cork-NBR, Cork-Neoprene',
      shore_hardness: 'Compressible (60–80 Shore A equivalent)',
      temp_rating: '-30°C to +120°C',
      applications: 'Transformer Gaskets, Gearbox & Engine Covers, Machine Mounts, Insulation Pads',
      features: 'High compressibility, oil resistant, low bolt load sealing, easily cut to shape',
      is_featured: false,
      order_index: 15
    },
    {
      category_code: 'P-06',
      name: 'Anti-Vibration Ribbed Rubber Pads',
      slug: 'anti-vibration-pads',
      image_url: '/uploads/products/anti-vibration-pads.jpg',
      subtitle: 'Ribbed rubber mounting pads for machinery isolation',
      short_desc: 'Heavy-duty ribbed rubber pads that absorb vibration and noise under machines, compressors and pumps.',
      full_desc: 'Cross-ribbed rubber pads that reduce transmitted vibration, shock and noise from rotating and reciprocating machinery. Supplied in standard sizes or cut from sheet to any footprint and stacked for greater deflection.',
      material_grades: 'Natural Rubber, Neoprene, NBR (oil-resistant)',
      shore_hardness: '50A–70A Shore',
      temp_rating: '-20°C to +80°C',
      applications: 'Compressors, Pumps, Generators, CNC Machines, HVAC Units, Presses',
      features: 'No bolting required, anti-skid, oil-resistant option, custom sizes',
      is_featured: false,
      order_index: 16
    },
    {
      category_code: 'P-06',
      name: 'Self-Adhesive Foam Sealing Tape',
      slug: 'foam-sealing-tape',
      image_url: '/uploads/products/foam-sealing-tape.jpg',
      subtitle: 'Closed-cell EPDM/Neoprene foam weather-strip',
      short_desc: 'Closed-cell sponge rubber tape with adhesive backing for sealing panels, doors and enclosures against dust and water.',
      full_desc: 'Closed-cell EPDM and neoprene sponge tape with a pressure-sensitive adhesive liner. Compresses easily to seal gaps in electrical panels, HVAC ducts, cabinets and doors, while resisting weather, ozone and moisture.',
      material_grades: 'EPDM Sponge, Neoprene Sponge, PVC Foam',
      shore_hardness: 'Soft closed-cell sponge',
      temp_rating: '-40°C to +100°C',
      applications: 'Electrical Panels, HVAC Ducting, Enclosures, Doors & Windows, Automotive',
      features: 'Peel-and-stick, waterproof & dustproof, weather resistant, multiple widths & thicknesses',
      is_featured: false,
      order_index: 17
    },
    {
      category_code: 'P-07',
      name: 'Silicone & EPDM Extruded Profiles',
      slug: 'silicone-extruded-profiles',
      image_url: '/uploads/products/silicone-extruded-profiles.jpg',
      gallery_images: ['/uploads/products/silicone-extruded-profiles-2.jpg'],
      subtitle: 'Custom D, P, E, U & hollow section seals and tubing',
      short_desc: 'Extruded silicone and EPDM profiles, tubes, sponge cords and moulded frame gaskets in any colour and cross-section.',
      full_desc: 'Silicone and EPDM rubber extruded to your drawing — D, P, E, U, J and multi-lumen hollow sections, solid square/rectangular strips and sponge cords. Profiles can be cut to length or vulcanised into endless frame gaskets for ovens, autoclaves and enclosures.',
      material_grades: 'Silicone (VMQ), Food Grade Silicone, Sponge Silicone, EPDM, Neoprene',
      shore_hardness: '30A–80A Shore',
      temp_rating: '-60°C to +230°C (silicone)',
      applications: 'Oven & Autoclave Doors, Pharma Equipment, Electrical Enclosures, Glass Glazing, Food Machinery',
      features: 'Any custom profile, colour options, FDA grade available, vulcanised corner joints',
      is_featured: true,
      order_index: 18
    },
    {
      category_code: 'P-08',
      name: 'PTFE Bellows',
      slug: 'ptfe-bellows',
      image_url: '/uploads/products/ptfe-bellows.jpg',
      subtitle: 'Machined convoluted PTFE bellows for corrosive media',
      short_desc: 'CNC-machined PTFE bellows and expansion joints for chemical pumps, valves and glass-lined equipment.',
      full_desc: 'Precision-machined convoluted PTFE bellows that absorb axial movement and misalignment while remaining fully inert to acids, alkalis and solvents. Used as mechanical seal bellows, valve stem seals and flexible connectors on glass-lined and FRP pipelines.',
      material_grades: 'Virgin PTFE, Modified PTFE (TFM)',
      shore_hardness: '55D–60D Shore',
      temp_rating: '-200°C to +200°C',
      applications: 'Chemical Pumps, Mechanical Seals, Valve Stems, Glass-Lined Reactors, FRP Pipelines',
      features: 'Complete chemical inertness, non-contaminating, custom convolution count & flange size',
      is_featured: false,
      order_index: 19
    },
    {
      category_code: 'P-08',
      name: 'Machine Way Cover Bellows',
      slug: 'machine-way-bellows',
      image_url: '/uploads/products/machine-way-bellows.jpg',
      subtitle: 'Rectangular folded bellow covers for machine slideways',
      short_desc: 'Folded protective bellow covers that shield CNC guideways, ball screws and slides from chips, coolant and dust.',
      full_desc: 'Rectangular accordion-type bellow covers fabricated from coated nylon or PVC fabric with internal stiffeners. They protect precision guideways, ball screws and hydraulic rams on machine tools from swarf, coolant and abrasive dust, extending machine accuracy and life.',
      material_grades: 'PVC Coated Polyester, PU Coated Nylon, Neoprene Coated Fabric',
      shore_hardness: 'Flexible fabric',
      temp_rating: '-20°C to +120°C',
      applications: 'CNC Machines, Milling & Grinding Machines, Lathes, Lift Tables, Hydraulic Presses',
      features: 'Made to machine dimensions, coolant & oil resistant, long stroke ratios',
      is_featured: false,
      order_index: 20
    },
    {
      category_code: 'P-08',
      name: 'Round Rubber Bellows & Boots',
      slug: 'round-rubber-bellows',
      image_url: '/uploads/products/round-rubber-bellows.jpg',
      subtitle: 'Moulded convoluted dust boots for shafts and rods',
      short_desc: 'Moulded round rubber bellows and dust boots protecting piston rods, shafts and joints from dirt and moisture.',
      full_desc: 'Convoluted rubber bellows and gaiters moulded in Neoprene, NBR, EPDM or Silicone. They seal moving shafts, piston rods, steering and drive joints, accommodating axial travel and angular movement while keeping contaminants out.',
      material_grades: 'Neoprene, NBR, EPDM, Silicone',
      shore_hardness: '50A–70A Shore',
      temp_rating: '-40°C to +150°C',
      applications: 'Hydraulic Rams, Lead Screws, Steering & CV Joints, Ducting Connections, Lift Equipment',
      features: 'Flexible in axial & angular movement, oil/ozone resistant, custom sizes',
      is_featured: false,
      order_index: 21
    },
    {
      category_code: 'P-08',
      name: 'Rubber Expansion Joints',
      slug: 'rubber-expansion-joints',
      image_url: '/uploads/products/rubber-expansion-joint.jpg',
      gallery_images: ['/uploads/products/rubber-expansion-joint-2.jpg', '/uploads/products/rubber-expansion-joint-3.jpg'],
      subtitle: 'Flanged single & double arch pipeline bellows',
      short_desc: 'Fabric-reinforced rubber expansion joints with MS/SS flanges to absorb pipeline movement, vibration and misalignment.',
      full_desc: 'Single-sphere and double-arch rubber expansion joints built with nylon tyre-cord reinforcement and backed by galvanised MS or SS flanges. They absorb thermal expansion, pump vibration and pipe misalignment, and reduce noise transmission in water, slurry and chemical pipelines.',
      material_grades: 'EPDM, Neoprene, NBR, Natural Rubber, Butyl — nylon cord reinforced',
      shore_hardness: '60A–70A Shore',
      temp_rating: '-20°C to +110°C',
      applications: 'Pump Suction & Delivery, Cooling Water Lines, HVAC Chillers, Slurry Pipelines, STP/ETP Plants',
      features: 'PN10/PN16 rated, galvanised MS/SS flanges, single & multi-arch, vibration & noise reduction',
      is_featured: true,
      order_index: 22
    },
    {
      category_code: 'P-09',
      name: 'Industrial Flange Gaskets',
      slug: 'industrial-flange-gaskets',
      image_url: '/uploads/products/industrial-gaskets.jpg',
      subtitle: 'Cut, spiral-wound & non-asbestos gaskets',
      short_desc: 'Non-asbestos, rubber, PTFE, cork, felt and spiral-wound gaskets cut to any flange standard or drawing.',
      full_desc: 'Complete range of flange and equipment gaskets — compressed non-asbestos fibre, rubber, PTFE envelope, cork, felt, adhesive-backed and metallic spiral-wound types. Cut to ASME/DIN/BS flange standards or to customer drawings for pipelines, pumps, heat exchangers and pressure vessels.',
      material_grades: 'CNAF, Spiral Wound SS316/Graphite, PTFE, EPDM, Neoprene, Cork, Felt, Viton',
      shore_hardness: 'Grade dependent',
      temp_rating: '-200°C to +550°C (grade dependent)',
      applications: 'Pipeline Flanges, Pumps & Valves, Heat Exchangers, Boilers, Pressure Vessels, Engine Covers',
      features: 'Any flange standard or custom drawing, high-pressure spiral-wound options, quick turnaround',
      is_featured: true,
      order_index: 23
    },
    {
      category_code: 'P-09',
      name: 'Plate Heat Exchanger (PHE) Gaskets',
      slug: 'phe-gaskets',
      image_url: '/uploads/products/phe-gasket.jpg',
      subtitle: 'Clip-on & glued replacement gaskets for PHE plates',
      short_desc: 'Replacement NBR & EPDM gaskets for plate heat exchangers — clip-on and glue-type designs for leading PHE models.',
      full_desc: 'Moulded replacement gaskets for plate heat exchangers in clip-on (glue-free) and glued designs. Compounded for hot water, steam, oils and food media, they restore full thermal performance and leak-tightness during PHE overhauls.',
      material_grades: 'NBR, HNBR, EPDM (peroxide cured), Viton (FKM)',
      shore_hardness: '70A–80A Shore',
      temp_rating: '-25°C to +160°C (grade dependent)',
      applications: 'HVAC & District Heating, Dairy & Food Processing, Chemical Plants, Marine Coolers, Power Plants',
      features: 'Clip-on & glued types, food grade available, exact OEM groove fit',
      is_featured: false,
      order_index: 24
    },
    {
      category_code: 'P-09',
      name: 'Felt Washers & Rings',
      slug: 'felt-washers',
      image_url: '/uploads/products/felt-washer.jpg',
      subtitle: 'Pressed wool felt washers, seals and polishing wheels',
      short_desc: 'Pressed wool felt washers and rings for dust sealing, lubricant retention and polishing applications.',
      full_desc: 'Precision-cut pressed wool felt washers, seals and wheels. Felt retains lubricant and excludes dust around bearings and shafts, cushions vibration, and is widely used for buffing and polishing operations.',
      material_grades: 'Pressed Wool Felt, Synthetic Felt',
      shore_hardness: 'Soft / Medium / Hard density',
      temp_rating: '-40°C to +100°C',
      applications: 'Bearing Dust Seals, Oil Wicks, Polishing Wheels, Anti-Rattle Pads, Instrument Mounts',
      features: 'Oil retention, dust exclusion, custom ID/OD/thickness, multiple densities',
      is_featured: false,
      order_index: 25
    },
    {
      category_code: 'P-10',
      name: 'Heavy Duty Rubber Bush',
      slug: 'heavy-duty-rubber-bush',
      image_url: '/uploads/products/rubber-bush.jpg',
      subtitle: 'Moulded rubber bushes, buffers & stoppers',
      short_desc: 'Thick-wall moulded rubber bushes and buffers for shock absorption, coupling and suspension duties.',
      full_desc: 'Solid thick-wall rubber bushes moulded to drawing for couplings, suspension pivots, buffer stops and machine mounts. Compounds are selected for load, oil exposure and temperature to deliver long service life under repeated impact.',
      material_grades: 'Natural Rubber, NBR, Neoprene, EPDM, PU',
      shore_hardness: '60A–90A Shore',
      temp_rating: '-30°C to +100°C',
      applications: 'Flexible Couplings, Crane Buffers, Vehicle Suspension, Vibratory Screens, Machine Mounts',
      features: 'High load capacity, shock & vibration damping, made to sample or drawing',
      is_featured: false,
      order_index: 26
    },
    {
      category_code: 'P-10',
      name: 'Rubber Pin / Bristle Pads',
      slug: 'rubber-pin-pads',
      image_url: '/uploads/products/rubber-pin-pad.jpg',
      gallery_images: ['/uploads/products/rubber-pin-pad-2.jpg'],
      subtitle: 'Moulded pin-type rubber pads with backing plate',
      short_desc: 'Moulded rubber pin pads with dense flexible pins — for gripping, cushioning and supporting products on conveyors and machines.',
      full_desc: 'Rubber pin (bristle) pads moulded with hundreds of flexible pins on a solid base, supplied loose or bonded to a metal backing plate. The pins grip and cushion workpieces without marking, and are used on conveyors, cutting tables, glass and tile handling lines and cleaning equipment.',
      material_grades: 'Natural Rubber, NBR, EPDM, Silicone, PU',
      shore_hardness: '50A–80A Shore',
      temp_rating: '-20°C to +120°C',
      applications: 'Conveyor Lines, Cutting Tables, Glass & Tile Handling, Cleaning Machines, Packaging Machines',
      features: 'Non-marking grip, flexible pins, metal backing plate option, custom pad size',
      is_featured: false,
      order_index: 27
    },
    {
      category_code: 'P-10',
      name: 'Logo-Embossed Custom Rubber Pads',
      slug: 'logo-embossed-rubber-pads',
      image_url: '/uploads/products/logo-embossed-rubber-pad.jpg',
      subtitle: 'Compression-moulded pads with embossed branding',
      short_desc: 'Custom moulded rubber pads and blocks with embossed or debossed logo, part number or text.',
      full_desc: 'Compression-moulded rubber pads, blocks and feet with your logo, part number or text moulded directly into the surface for permanent identification. Made to drawing in the required thickness, hardness and compound.',
      material_grades: 'Natural Rubber, NBR, Neoprene, EPDM, Silicone',
      shore_hardness: '50A–90A Shore',
      temp_rating: '-30°C to +120°C',
      applications: 'Machine Feet, Wear Pads, Anti-Slip Pads, OEM Branded Spares, Mounting Blocks',
      features: 'Permanent moulded branding, custom size & hardness, traceable part marking',
      is_featured: false,
      order_index: 28
    },
    {
      category_code: 'P-11',
      name: 'O-Ring Service Kit (NBR-70, 386 pcs)',
      slug: 'o-ring-service-kit',
      image_url: '/uploads/products/o-ring-service-kit.jpg',
      subtitle: 'Metric size series — 30 sizes, 386 pieces',
      short_desc: 'NBR-70 metric O-ring assortment box with 30 sizes (3×2 to 44×4 mm), 386 pieces — RoHS compliant.',
      full_desc: 'Ready-to-use O-ring service kit in a compartmented carry box for maintenance workshops. Contains 386 NBR-70 O-rings in 30 metric sizes from 3×2 mm to 44×4 mm, manufactured to ASTM D2000 M2BG714 and RoHS compliant.',
      material_grades: 'NBR-70 (ASTM D2000 M2BG714 A14 B14 EA14 EF11 EF21 EO21 EO14 EO34 F17)',
      shore_hardness: '70A Shore',
      temp_rating: '-30°C to +100°C',
      applications: 'Maintenance Workshops, Hydraulic & Pneumatic Repairs, Automotive Service, Plant Stores',
      features: '30 metric sizes, 386 pcs, labelled compartments, RoHS compliant',
      is_featured: false,
      order_index: 29
    },
    {
      category_code: 'P-11',
      name: 'Circlip External Assortment Kit',
      slug: 'circlip-external-kit',
      image_url: '/uploads/products/circlip-external-kit.jpg',
      subtitle: 'Shaft circlips 4mm–26mm, 30 nos per size',
      short_desc: 'External (shaft) circlip kit with 13 sizes from 4mm to 26mm, 30 pieces each, in a compartmented box.',
      full_desc: 'SDE external circlip assortment kit for shafts, packed in a clear compartmented organiser. Includes 30 pieces each of 4, 5, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24 and 26 mm sizes — 390 circlips in total for quick maintenance replacement.',
      material_grades: 'Spring Steel, Phosphate/Black Oxide finish',
      shore_hardness: '',
      temp_rating: '',
      applications: 'Maintenance Workshops, Gearboxes, Pumps, Motors, Automotive & Machine Repair',
      features: '13 sizes (4–26 mm), 30 nos per size, labelled compartments',
      is_featured: false,
      order_index: 30
    },
    {
      category_code: 'P-11',
      name: 'Circlip Internal Assortment Kit',
      slug: 'circlip-internal-kit',
      image_url: '/uploads/products/circlip-internal-kit.jpg',
      subtitle: 'Bore circlips 8mm–34mm, 30 nos per size',
      short_desc: 'Internal (bore) circlip kit with 13 sizes from 8mm to 34mm, 30 pieces each, in a compartmented box.',
      full_desc: 'SDE internal circlip assortment kit for bores, packed in a clear compartmented organiser. Includes 30 pieces each of 8, 10, 12, 14, 16, 18, 20, 24, 26, 28, 30, 32 and 34 mm sizes — 390 circlips in total for quick maintenance replacement.',
      material_grades: 'Spring Steel, Phosphate/Black Oxide finish',
      shore_hardness: '',
      temp_rating: '',
      applications: 'Maintenance Workshops, Bearing Housings, Gearboxes, Pumps, Hydraulic Cylinders',
      features: '13 sizes (8–34 mm), 30 nos per size, labelled compartments',
      is_featured: false,
      order_index: 31
    }
  ],

  industries: [
    { name: 'Chemical', icon: 'FlaskConical', description: 'Acid-resistant PTFE, Viton & FFKM seals for harsh chemical environments.', order_index: 1 },
    { name: 'Pharma', icon: 'Pill', description: 'FDA & USP Class VI sanitary silicone gaskets and NovAseptic diaphragms.', order_index: 2 },
    { name: 'Food Processing', icon: 'Utensils', description: 'Cleanroom food-grade elastomers, non-toxic PU conveyor wheels and belts.', order_index: 3 },
    { name: 'Cement', icon: 'Building2', description: 'Heavy-duty high-temp bellows and rugged hydraulic cylinder seal kits.', order_index: 4 },
    { name: 'Steel', icon: 'Hammer', description: 'Furnace-side 1400°C bellows and shock-absorbing polyurethane pads.', order_index: 5 },
    { name: 'Paper', icon: 'FileText', description: 'Chemical-resistant rubber roll covers and water-lubricated nylon bushes.', order_index: 6 },
    { name: 'Packaging', icon: 'Box', description: 'High-speed suction cups, silicone heat-sealing strips and PU rollers.', order_index: 7 },
    { name: 'Plastic', icon: 'Layers', description: 'Extruder barrel seals, mould wiper rings, and heat-resistant gaskets.', order_index: 8 },
    { name: 'Textile', icon: 'Scissors', description: 'Yarn guiding wear rings, anti-static PU wheels, and dyeing vessel seals.', order_index: 9 },
    { name: 'Power', icon: 'Zap', description: 'Flue gas expansion joints, turbine sealing components & insulated mats.', order_index: 10 },
    { name: 'OEM', icon: 'Cpu', description: 'Custom engineered polymer parts matched to production machinery tolerances.', order_index: 11 },
    { name: 'Heavy Engineering', icon: 'Cog', description: 'Excavator cylinder kits, high-pressure oil seals & precision polymer bushes.', order_index: 12 }
  ],

  whyChoose: [
    { title: 'Custom Design & Development', description: 'Engineered to your exact 2D/3D drawing or physical sample part.', icon: 'PenTool', order_index: 1 },
    { title: 'Reverse Engineering', description: 'Worn or obsolete part in hand — we rebuild and certify the exact spec.', icon: 'RotateCw', order_index: 2 },
    { title: 'OEM Replacement Parts', description: 'High-precision import substitutes matched to original factory tolerances.', icon: 'CheckSquare', order_index: 3 },
    { title: 'Fast Manufacturing', description: 'In-house tooling and die development keeps turnaround times industry-leading.', icon: 'Zap', order_index: 4 },
    { title: 'Quality Tested Products', description: 'Every batch checked for shore hardness, tensile strength, and micrometer tolerance.', icon: 'ShieldCheck', order_index: 5 },
    { title: 'Bulk Supply', description: 'Consistent high-tolerance output across massive industrial production runs.', icon: 'Package', order_index: 6 },
    { title: 'Emergency Deliveries', description: 'Critical plant breakdown? We prioritize expedited manufacturing and dispatch.', icon: 'Clock', order_index: 7 },
    { title: 'Technical Support', description: 'Material grade, durometer, and chemical compatibility guidance before you order.', icon: 'Headphones', order_index: 8 }
  ],

  processSteps: [
    { step_number: '01', title: 'Share Drawing / Sample', description: 'Send your technical spec, 2D/3D CAD drawing or worn component sample.', order_index: 1 },
    { step_number: '02', title: 'Technical Review', description: 'Our polymer engineering team assesses pressure, temperature & chemical tolerances.', order_index: 2 },
    { step_number: '03', title: 'Material Selection', description: 'We select the optimum polymer grade (NBR, Viton, PU, PTFE, Silicone) for your medium.', order_index: 3 },
    { step_number: '04', title: 'Sample Development', description: 'First-off prototype or pre-production sample manufactured for your test approval.', order_index: 4 },
    { step_number: '05', title: 'Production at Scale', description: 'High-precision batch moulding or CNC machining in our Vadodara manufacturing plant.', order_index: 5 },
    { step_number: '06', title: 'Quality Check & Dispatch', description: '100% inspected, securely packed, and fast dispatched across India & globally.', order_index: 6 }
  ],

  applications: [
    { title: 'Hydraulic Systems', description: 'Cylinders, seal kits, wear rings & pressure accumulators', category_tag: 'Fluid Power', order_index: 1 },
    { title: 'Pneumatic Systems', description: 'Piston seals, wiper seals, rod packings & cushion rings', category_tag: 'Pneumatics', order_index: 2 },
    { title: 'Pumps & Valves', description: 'Flange gaskets, mechanical seal O-rings & diaphragms', category_tag: 'Process', order_index: 3 },
    { title: 'Compressors', description: 'High-temperature seals, valve plates & oil baffles', category_tag: 'Heavy Machinery', order_index: 4 },
    { title: 'Conveyors', description: 'Polyurethane wheels, rollers, bumper blocks & guide sleeves', category_tag: 'Material Handling', order_index: 5 },
    { title: 'Gearboxes', description: 'Rotary oil seals, shaft isolators, bush & stoppers', category_tag: 'Transmission', order_index: 6 },
    { title: 'Process Plants', description: 'Expansion joints, high-flex PTFE bellows & tank seals', category_tag: 'Plants & Piping', order_index: 7 },
    { title: 'Furnaces & Kilns', description: 'PTFE & 1400°C fireproof high-temperature fabric bellows', category_tag: 'Thermal', order_index: 8 }
  ],

  trustPoints: [
    { title: 'Manufacturing Capability', description: 'In-house tooling & moulding across 10 distinct polymer product families.', order_index: 1 },
    { title: 'Quality Inspection', description: 'Every single batch tested for shore hardness, tensile resilience & dimensional tolerance.', order_index: 2 },
    { title: 'Complete Customization', description: 'Any size, shape, colour, and shore hardness durometer (25A to 95A & 90D).', order_index: 3 },
    { title: 'Expert Engineering Support', description: 'Decades of polymer application and chemical resistance expertise included.', order_index: 4 },
    { title: '24-Hour Rapid Response', description: 'Detailed technical quotation and engineering consultation delivered within 24 hours.', order_index: 5 }
  ]
};

module.exports = initialData;
